// `@lntt/scope/react-router` — the React Router carrier and its two mounts.
//
// A carrier is `__args` alone (§43). A loader and an action carry the same
// `{ request, params }` pair, so ONE carrier serves both — but they are two
// DISTINCT mount shapes and never a generic middleware: each runs to
// completion on its own, once, for its own route. That is why there is no
// `mw` here.
//
// `context` — React Router's own per-request bag — is deliberately left out of
// `__args`: a mount adds it back at the specific type it actually receives, the
// same way an Express route reads `Request`/`Response` at the width it needs.

import type { Params } from 'react-router'
import type { DepGuard, Next, Passed, ResultOf, Scope, State } from '../index.ts'
import type { StandardIssue } from '../guard/index.ts'
import {
  cookiesFrom,
  headersFrom,
  queryFrom,
  readBody,
  type BodyOf,
  type Cookies,
  type Encoding,
  type Headers_ as HeaderRecord,
  type Query,
} from '../reads.ts'

// `Par` is what the scope says the route supplies. It defaults to React
// Router's own `Params`, whose values are `string | undefined`; a route module
// generated by RR7's typegen can hand its own in —
// `reactRouterCarrier<Route.LoaderArgs['params']>()` — and then `params.id` is
// a `string` inside every step, with no `!` anywhere.
export interface ReactRouterCarrier<Par = Params> {
  readonly __args?: { readonly request: Request; readonly params: Par }
}

// PURE DECLARATION — the returned object carries nothing; the type argument is
// the whole point of the call.
export const reactRouterCarrier = <Par = Params>(): ReactRouterCarrier<Par> => ({})

// `loader` and `action` are the same wrapper twice, and stay two names on
// purpose: which one a route exports is what React Router reads, so collapsing
// them into one `mount` would hand the author a value that fits both slots and
// says nothing about which it is.
//
// THE MOUNT IS TRANSPARENT: it hands back what the SCOPE hands back, so
// `useLoaderData<typeof loader>()` and RR7's own typegen see the leaf's value.
// Declared `unknown` — which is what a wrapper writes by default — they would
// see `unknown` instead, and nothing at runtime would say so.
//
// A step that stops does so in React Router's own door — a THROWN `data(...)`
// or `redirect(...)`. A RETURNED `data(null, { status: 404 })` renders normally
// instead of reaching an ErrorBoundary, and nothing here guards against writing
// `return` by mistake: the mistake is at the call site, not at a missing check.
export const reactRouter = <App extends object>(deps: App) => {
  // `DepGuard` rides the scope argument: the deps were curried at
  // `reactRouter(deps)`, so a mount hands the scope its chain exactly as a
  // direct call does and owes the same verdict — without it, the mount would be
  // the one way to reach a scope while supplying less than it asks.
  const mount =
    <S extends State>(sc: Scope<S> & DepGuard<App, S['need']>) =>
    (args: S['args']): Promise<ResultOf<Scope<S>>> =>
      (sc as unknown as (app: App, a: object) => Promise<ResultOf<Scope<S>>>)(deps, args)

  return { loader: mount, action: mount }
}

// ── the read extensions ──────────────────────────────────────────────────────
// PLAIN STEPS, not verbs: these ADD a ctx entry, and a verb is what may REPLACE
// one (`@lntt/scope/guard`). The reasoning is written out in the Hono carrier;
// these two are the SAME FAMILY — both read a Fetch `Request` — so what differs
// is only where the request is found, and the readers themselves are shared.
export type { Query, Cookies, Headers_ as HeaderEntries, Encoding, BodyOf } from '../reads.ts'

export const query = async (
  _app: {},
  { request }: { readonly request: Request },
  next: Next<{ query: Query }>,
) => next({ query: queryFrom(new URL(request.url).searchParams) })

export const headers = async (
  _app: {},
  { request }: { readonly request: Request },
  next: Next<{ headers: HeaderRecord }>,
) => next({ headers: headersFrom(request.headers) })

export const cookies = async (
  _app: {},
  { request }: { readonly request: Request },
  next: Next<{ cookies: Cookies }>,
) => next({ cookies: cookiesFrom(request.headers.get('cookie')) })

// A loader has no body; an ACTION does. The step reads whichever request the run
// brought, so one factory serves both and the mount decides which it is.
export const body =
  <E extends Encoding, R>(
    encoding: E,
    onError: (issues: readonly StandardIssue[], ctx: { readonly request: Request }) => R,
  ) =>
  async (
    _app: {},
    ctx: { readonly request: Request },
    next: Next<{ body: BodyOf<E> }>,
  ): Promise<Passed | Awaited<R>> => {
    const read = await readBody(ctx.request, encoding)
    if ('issues' in read) return onError(read.issues, ctx) as Awaited<R>
    return next({ body: read.value as BodyOf<E> })
  }
