// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/posts/:postId": {
    params: {
      "postId": string;
    };
  };
  "/feed.csv": {
    params: {};
  };
  "/posts/new": {
    params: {};
  };
  "/me": {
    params: {};
  };
  "/native": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/verify": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/dev/outbox": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/posts/:postId" | "/feed.csv" | "/posts/new" | "/me" | "/native" | "/login" | "/verify" | "/logout" | "/dev/outbox";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/post.tsx": {
    id: "routes/post";
    page: "/posts/:postId";
  };
  "routes/feed-csv.tsx": {
    id: "routes/feed-csv";
    page: "/feed.csv";
  };
  "routes/publish.tsx": {
    id: "routes/publish";
    page: "/posts/new";
  };
  "routes/me.tsx": {
    id: "routes/me";
    page: "/me";
  };
  "routes/native.tsx": {
    id: "routes/native";
    page: "/native";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/verify.tsx": {
    id: "routes/verify";
    page: "/verify";
  };
  "routes/logout.ts": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/dev.outbox.ts": {
    id: "routes/dev.outbox";
    page: "/dev/outbox";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/post": typeof import("./app/routes/post.tsx");
  "routes/feed-csv": typeof import("./app/routes/feed-csv.tsx");
  "routes/publish": typeof import("./app/routes/publish.tsx");
  "routes/me": typeof import("./app/routes/me.tsx");
  "routes/native": typeof import("./app/routes/native.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/verify": typeof import("./app/routes/verify.tsx");
  "routes/logout": typeof import("./app/routes/logout.ts");
  "routes/dev.outbox": typeof import("./app/routes/dev.outbox.ts");
};