// A STAND-IN FOR RR7's TYPEGEN, and the one shortcut this example takes.
//
// In a real app these come from `./+types/<route>`, generated by React Router
// from `routes.ts` — running `react-router typegen` needs the app's build
// pipeline, which is more machinery than this example's point is worth. The
// SHAPES are what the typegen really produces, and that is what matters here:
// a route's params typed from its own path.
//
// Nothing downstream knows the difference — the check demonstrated in
// `routes.test.ts` is `satisfies`, and it reads whichever of the two is
// imported.
export declare namespace PostRoute {
  type LoaderArgs = { request: Request; params: { id: string }; context: unknown }
  type ActionArgs = { request: Request; params: { id: string }; context: unknown }
}

export declare namespace PostsRoute {
  type ActionArgs = { request: Request; params: {}; context: unknown }
}

// What the typegen would produce for a route mounted at a DIFFERENT path —
// used to show the refusal, and never mounted.
export declare namespace WrongRoute {
  type LoaderArgs = { request: Request; params: { slug: string }; context: unknown }
}
